In [1]:
#creating the predictions on for the server

In [2]:
import pickle
import os
import torch

In [3]:
from PIL import Image
import numpy as np

def array_to_img(image):
    img = Image.fromarray(image,)
    img.show()

In [4]:
#open the testfile
import pickle
import os
with open(os.path.join('data','testset.pkl'), 'rb') as pickle_file:
    arrays = pickle.load(pickle_file)
len(arrays['input_arrays'])

208

In [5]:
# import the model:
model = torch.load(os.path.join("colab", "my_pc_cnn.pt"),map_location=torch.device('cpu'))

In [6]:
model

CNN(
  (hidden_layers): Sequential(
    (0): Conv2d(1, 32, kernel_size=(7, 7), stride=(1, 1))
    (1): ReLU()
    (2): Conv2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (3): ReLU()
    (4): Conv2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (5): ReLU()
    (6): ConvTranspose2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (7): ReLU()
    (8): ConvTranspose2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (9): ReLU()
    (10): ConvTranspose2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (11): ReLU()
    (12): ConvTranspose2d(32, 32, kernel_size=(7, 7), stride=(1, 1))
    (13): ReLU()
  )
  (output_layer): Conv2d(32, 1, kernel_size=(7, 7), stride=(1, 1))
  (linear1): Linear(in_features=8100, out_features=8100, bias=True)
)

In [7]:
#creating the predictions
predictions_img = []
predictions_server = []
for i in range(len(arrays['input_arrays'])):
    inp = arrays['input_arrays'][i].reshape(1,1,90,90)
    out = model(torch.tensor(inp,dtype = torch.float32)/255)
    predictions_img.append(out*255)
    mask = arrays['known_arrays'][i]
    predictions_server.append(np.array((out[0][0]*255)[mask==0].detach().numpy(),dtype=np.uint8))

In [8]:
array_to_img(arrays['input_arrays'][1])

In [9]:
#looking at an image
for r in range(10):
    array_to_img(predictions_img[r][0][0].detach().numpy())
    

In [8]:
#creating the submissions file

In [12]:
with open(os.path.join('data','cnn_final_prediction.pkl'), 'wb') as pickle_file:
    pickle.dump(predictions_server, pickle_file)

In [10]:
#open the testfile
import pickle
import os
with open(os.path.join('data','cnn_final_prediction.pkl'), 'rb') as pickle_file:
    convolution = pickle.load(pickle_file)
convolution

[array([ 98, 100,  99, ...,  60,  62,  63], dtype=uint8),
 array([235, 242, 243, ...,  36,  39,  41], dtype=uint8),
 array([ 99, 101, 101, ...,  93,  94,  93], dtype=uint8),
 array([166, 181, 189, ...,  20,  23,  26], dtype=uint8),
 array([26, 23, 22, ..., 56, 59, 60], dtype=uint8),
 array([145, 153, 156, ...,  65,  65,  63], dtype=uint8),
 array([109, 110, 109, ..., 115, 115, 110], dtype=uint8),
 array([143, 157, 163, ...,  63,  66,  67], dtype=uint8),
 array([155, 159, 159, ..., 108, 108, 103], dtype=uint8),
 array([183, 186, 184, ..., 157, 153, 141], dtype=uint8),
 array([ 84,  85,  84, ..., 109, 108, 104], dtype=uint8),
 array([ 60,  61,  62, ..., 107, 107, 102], dtype=uint8),
 array([211, 217, 216, ..., 125, 125, 119], dtype=uint8),
 array([69, 71, 71, ..., 98, 99, 95], dtype=uint8),
 array([227, 234, 235, ...,  25,  28,  31], dtype=uint8),
 array([212, 219, 220, ...,  96,  95,  90], dtype=uint8),
 array([80, 81, 79, ..., 71, 72, 71], dtype=uint8),
 array([114, 117, 116, ..., 107,

In [11]:
#open the testfile
import pickle
import os
with open(os.path.join('data','testset_submission_random.pkl'), 'rb') as pickle_file:
    random = pickle.load(pickle_file)
random[0].shape

(2324,)

In [88]:
mask = np.array([[0,1,1,0],[0,1,1,0],[0,1,1,0],[0,1,1,0],])
arr = np.random.randint(0,255,(4,4))
arr

array([[118, 225, 107, 251],
       [193, 102, 192,  42],
       [127,  13,  49,  30],
       [230,  24, 131, 154]])

In [90]:
mask

array([[0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0]])

In [96]:
arr[mask==0]

array([118, 251, 193,  42, 127,  30, 230, 154])

In [94]:
arrays['known_arrays'][0][9]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0], dtype=uint8)